---
# tasks file for cca.splunk.enterprise-install
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2025.3.1

- name: Perform a rolling upgrade of Splunk Search Head Cluster
  ansible.builtin.include_tasks: shcluster/shcluster_rolling_upgrade.yml
  when: shc_upgrade_method | default('rolling') == 'rolling'

- name: Perform a single upgrade of Splunk Search Head Cluster
  ansible.builtin.include_tasks: shcluster/shcluster_member_by_member_upgrade.yml
  when: shc_upgrade_method | default('') == 'member_by_member'

- name: Check if current search head member was captain when upgrade started
  ansible.builtin.stat:
    path: "{{ searchhead_captain }}"
  register: searchhead_captain_stat
