---
# tasks file for cca.splunk.enterprise-install
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.1.1

- name: Find Splunk install file in repo directory
  become: false
  delegate_to: localhost
  connection: local
  ansible.builtin.find:
    paths: "{{ absolute_infra_repo_path }}/splunk/var/images/"
    patterns: "splunk-{{ splunk_enterprise_version }}-*64.tgz"
  register: find_cca_splunk_tgz

- name: Assert that we have a splunk tar file
  become: false
  delegate_to: localhost
  connection: local
  ansible.builtin.assert:
    that:
      find_cca_splunk_tgz.files | length == 1
    fail_msg: >-
      Found {{ find_cca_splunk_tgz.files | length }} Splunk tar file on the
      host that matches splunk-{{ splunk_enterprise_version }}-*64.tgz.
      It needs to be exaclty one, and we found these {{ find_cca_splunk_tgz.files }}
  when:
    - not stat_splunk_enterprise_bin.stat.exists or
      enterprise_upgrade | default(false)

- name: Stage splunk_cca files used during initial install or upgrade of Splunk Enterprise
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ cca_splunk_var_tmp }}/"
    recursive: true
    checksum: true
    archive: false
    rsync_path: 'sudo -u {{ splunk_user }} rsync'
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_opts:
      - "--include=dat/untracked_files_splunk_{{ splunk_enterprise_version }}_Linux.diff"
      - "--include=bin/sudo_ansible_helper.sh"
      - "--include=bin/splunk_upgrade_cleanup.sh"
      - "--exclude=dat/*"
  check_mode: false

- name: Stage Splunk tgz file at initial install or upgrade of Splunk Enterprise
  ansible.builtin.synchronize:
    src: "{{ absolute_infra_repo_path }}/splunk/var/images/"
    dest: "{{ cca_splunk_var_tmp }}/"
    recursive: true
    checksum: true
    archive: false
    rsync_path: 'sudo -u {{ splunk_user }} rsync'
    use_ssh_args: "{{ synchronize_module_use_ssh_args | default(false) }}"
    rsync_opts:
      - "--include=splunk-{{ splunk_enterprise_version }}-*-Linux-x86_64.tgz"
      - "--exclude=*"
  check_mode: false
