---
# tasks file for cca.splunk.onboarding
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
# TODO: Make staging of files independent on check mode, i.e., set checkmode on all tasks
# TODO: Add a random variable to the temp directories so that we avoid race conditions
- name: Cleanup manager before staging apps
  become: false
  ansible.builtin.file:
    path: '/tmp/{{ inventory_hostname }}/{{ shcluster }}'
    state: absent
  delegate_to: localhost
  when:
    - shcluster is defined
  changed_when: false
  check_mode: false

- name: Stage manager with shcluster apps from shcluster directory
  become: false
  ansible.builtin.copy:
    src: '{{ absolute_file_store_path }}/etc/{{ shcluster_apps_sourcedir }}/'
    dest: '/tmp/{{ inventory_hostname }}/{{ shcluster }}/apps/'
    remote_src: true
    mode: 'preserve'
  delegate_to: localhost
  when:
    - shcluster is defined
  changed_when: false
  check_mode: false

- name: Stage manager with shcluster generic apps
  become: false
  ansible.builtin.copy:
    src: '{{ absolute_file_store_path }}/etc/{{ shcluster_generic_sourcedir }}/{{ item.source_app }}/'
    dest: '/tmp/{{ inventory_hostname }}/{{ shcluster }}/apps/{{ item.name }}/'
    remote_src: true
    mode: 'preserve'
  delegate_to: localhost
  when:
    - shcluster_generic_sourcedir is defined
    - item.state is defined
    - item.state != 'absent'
  loop: '{{ generic_shcluster_apps | default([]) if generic_shcluster_apps | default([]) is iterable else [] }}'
  changed_when: false
  check_mode: false

- name: Stage manager with generic apps
  become: false
  ansible.builtin.copy:
    src: '{{ absolute_file_store_path }}/etc/{{ apps_generic_sourcedir }}/{{ item.source_app }}/'
    dest: '/tmp/{{ inventory_hostname }}/{{ shcluster }}/apps/{{ item.name }}/'
    remote_src: true
    mode: 'preserve'
  delegate_to: localhost
  when:
    - apps_generic_sourcedir is defined
    - item.state is defined
    - item.state != 'absent'
    - item.dest_dir == 'shcluster/apps'
  loop: '{{ versioned_apps | default([]) if versioned_apps | default([]) is iterable else [] }}'
  changed_when: false
  check_mode: false

- name: Include and run tasks from custom onboarding roles
  ansible.builtin.include_role:
    name: '{{ external_onboarding_role }}'
  loop_control:
    loop_var: external_onboarding_role
  loop: '{{ external_onboarding_shcluster_roles | default([]) if external_onboarding_shcluster_roles | default([]) is iterable else [] }}'
