---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.2.1


- name: Put SELinux in desired mode, permissive logs actions that would be blocked.
  selinux:
    policy: targeted
    state: "{{ cca_selinux_state | default('permissive') }}"
