---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.2.1
- name: Include tasks that will install/upgrade polkit
  include_tasks: "polkit/{{ package_manager }}/ensure_polkit.yml"

- name: Configure polkit for splunk
  include_tasks: polkit/polkit_rules.yml
