---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: André Enemark
#
# Release: 2022.2.4

- ansible.builtin.set_fact:
    current_item:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
  with_dict:
    - "{{ secret_type }}"

- ansible.builtin.set_fact:
    tmp_key: "{{ current_item.key }}_{{ current_item.value}}"

- ansible.builtin.set_fact:
    secret_password: "{{ vars_current_wizard[tmp_key] if cca_identical == true else random_pass4SymmKey.stdout }}"

- name: Encrypt the password
  ansible.builtin.shell:
    cmd: "{{ splunk_path }}/bin/splunk show-encrypted --value '{{ secret_password }}'"
  register: encrypted_random_secret

- name: Vault the secret password
  ansible.builtin.shell:
    cmd: "ansible-vault encrypt_string '{{ secret_password }}' | {{ sed_cmd }} ':a; N; $!ba; s/\\n/#/g' | {{ sed_cmd }} 's/[[:space:]]*//g' | {{ sed_cmd }} 's/|#/ \"/' | {{ sed_cmd }} 's/$/\"/'"
  register: vault_secret_result

- name: Save the clear text secret as an ansible vault
  ansible.builtin.lineinfile:
    path: "{{ vars.cca_splunk_secret_file }}"
    line: "{{ current_item.key }}_{{ current_item.value}}: {{ vault_secret_result.stdout | replace('#','\\r\\n') }}"
    regex: '^{{ current_item.key }}_{{ current_item.value}}:'

- name: Save the hashed secret to the file
  ansible.builtin.lineinfile:
    path: "{{ vars.cca_splunk_secret_file }}"
    line: "{{ current_item.key }}_{{ current_item.value}}_hash: '{{ encrypted_random_secret.stdout }}'"
    regex: '^{{ current_item.key }}_{{ current_item.value}}_hash:'
