---
# tasks file for cca.common.setup-wizard
#
# Description:
#
# Prerequisite:
#
# Author: André Enemark
#
# Release: 2022.2.1

- name: Check if Splunk is installed in temp location
  ansible.builtin.stat:
    path: "{{ splunk_path }}/bin/splunk"
  register: stat_splunk_enterprise_bin

- name: Get stat from splunk.secret file
  ansible.builtin.stat:
    path: "{{ splunk_path }}/etc/auth/splunk.secret"
    checksum_algorithm: "sha256"
  register: stat_splunk_secret

- name: If we have a splunk installation but no secrets file we have to copy the wizards config to the path
  ansible.builtin.file:
    path: "{{ splunk_path }}/etc/auth/splunk.secret"
    state: touch
  when:
    - not stat_splunk_secret.stat.exists

- name: Ensure manged splunk.secret file for new installations
  ansible.builtin.copy:
    content: "{{ vars_current_wizard.cca_splunk_secret }}"
    dest: "{{ splunk_path }}/etc/auth/splunk.secret"
    mode: '0400'
  register: result_splunk_secret_copy
  when:
    - not stat_splunk_secret.stat.exists
    - stat_cca_splunk_secret_file.stat.exists

- name: Check if current splunk version is installed
  ansible.builtin.shell:
    cmd: "{{ splunk_path }}/bin/splunk version --accept-license --no-prompt"
  register: splunk_enterprise_version_result
  when: stat_splunk_enterprise_bin.stat.exists

- name: Get stat from splunk.secret file
  ansible.builtin.stat:
    path: "{{ splunk_path }}/etc/auth/splunk.secret"
    checksum_algorithm: "sha256"
  register: stat_splunk_secret

- name: Get secret
  ansible.builtin.shell:
    cmd: "cat {{ splunk_path }}/etc/auth/splunk.secret"
  register: splunk_secret_result
  when:
    - stat_splunk_secret.stat.exists
    - stat_splunk_enterprise_bin.stat.exists

