---
# tasks file for deslicer.splunk.enterprise
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/deslicer)
#
# Release: 0.1.17

- name: Perform a rolling upgrade of Splunk Search Head Cluster
  ansible.builtin.include_tasks: shcluster/shcluster_rolling_upgrade.yml
  when: shc_upgrade_method | default('rolling') == 'rolling'

- name: Check if current search head member was captain when upgrade started
  ansible.builtin.stat:
    path: "{{ searchhead_captain }}"
  register: searchhead_captain_stat
