---
# tasks file for cca.splunk.ssl-certificates
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2023.3.1

# facts_variable: 'cca_splunk_inputs_ssl' is set in validate_manual_certificates.yml
# for manual certs or as a fallback here if the cert enrollment method is selfsigned
- name: Set fact for inputs cert to be used in common tasks
  ansible.builtin.set_fact:
    cert_file_name: '{{ cca_splunk_certs_inputs_cert }}'
    cert_staging_file_name: '{{ cca_splunk_certs_inputs_staging_cert }}'
    privkey_file_name: '{{ cca_splunk_certs_inputs_key }}'
    privkey_staging_file_name: '{{ cca_splunk_certs_inputs_staging_key }}'
    privkey_password: '{{ cca_splunk_certs_inputs_sslpassword }}'
    facts_variable: 'cca_splunk_inputs_ssl'
    cert_type: 'inputs'
  no_log: "{{ hide_password }}"

- name: Validate manual certs to find if they need updates
  include_tasks: validate_manual_certificates.yml
  when:
    - cca_splunk_cert_enrollment_method == 'manual'

- name: Include task to deploy manual certs
  include_tasks: deploy_manual_certs.yml
  when:
    - cca_splunk_cert_enrollment_method == 'manual'
    - final_cert_file_result.changed

- name: "Set fact if {{ cert_type }} cert is found and valid"
  ansible.builtin.set_fact:
    {"{{ facts_variable }}":true}
  when:
    - cca_splunk_cert_enrollment_method == 'selfsigned'
