

 Server has been configured with DAP for Splunk.

  ____    _    ____     __              ____        _             _
 |  _ \  / \  |  _ \   / _| ___  _ __  / ___| _ __ | |_   _ _ __ | | __
 | | | |/ _ \ | |_) | | |_ / _ \| '__| \___ \| '_ \| | | | | '_ \| |/ /
 | |_| / ___ \|  __/  |  _| (_) | |     ___) | |_) | | |_| | | | |   <
 |____/_/   \_\_|     |_|  \___/|_|    |____/| .__/|_|\__,_|_| |_|_|\_\
                                             |_| by Deslicer

 While support is not included in this version, support is available as part
 of Declicer Automation Platform. If interested, find more details at
 https://deslicer.com
