---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Author: Robin Blomdahl
#
# Release: 2023.3.2

- name: Install wanted baseline software on server
  ansible.builtin.apt:
    name: "{{ ensure_baseline_software }}"
    state: present
  loop_control:
    loop_var: ensure_baseline_software
  loop: '{{ cca_baseline_software | default([]) if cca_baseline_software | default([]) is iterable else [] }}'
