---
# tasks file for cca.splunk.frontend
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1
- name: Touch a file to suppress first time logging in message
  ansible.builtin.file:
    path: "{{ splunk_path }}/etc/.ui_login"
    state: touch
  changed_when: false
