---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Roger Lindquist (github.com/rlinq)
#
# Release: 2025.1.1


- name: Get running cgroup version
  ansible.builtin.command:
    cmd: |
      grep -c "group2 /sys/fs/cgroup cgroup2" /etc/mtab
  register: cgroup_version_result
  changed_when: false
  failed_when:
    - cgroup_version_result.rc > 1

- name: Get supported cgroup version 2
  ansible.builtin.command:
    cmd: |
      grep -c "cgroup2 /sys/fs/cgroup.* cgroup2" /etc/mtab
  register: cgroupv2_version_result
  changed_when: false
  failed_when:
    - cgroupv2_version_result.rc > 1

- name: Set running kernel cgroup version and supported version
  ansible.builtin.set_fact:
    running_kernel_cgroup_version: "{{ 'cgroupv1' if cgroup_version_result.stdout | int == 0 else 'cgroupv2' }}"
    supported_kernel_cgroup_version: "{{ 'cgroupv1' if cgroupv2_version_result.stdout | int == 0 else 'cgroupv2' }}"

- name: Get current configured systemd cgroup version
  ansible.builtin.command:
    cmd: |
      grep -c "cgroup /sys/fs/cgroup/systemd cgroup" /etc/mtab
  register: systemd_cgroup_version_result
  changed_when: false
  failed_when:
    - systemd_cgroup_version_result.rc > 1

- name: Set current systemd cgroup version
  ansible.builtin.set_fact:
    current_systemd_cgroup_version: "{{ 'cgroupv1' if systemd_cgroup_version_result.stdout | int == 1 else 'cgroupv2' }}"

- name: Include task to configure cgroupv1
  ansible.builtin.include_tasks: manage_cgroup_v1.yml
  when:
    - running_kernel_cgroup_version != 'cgroupv1'
    - current_systemd_cgroup_version != 'cgroupv1'
    - (
        (splunk_enterprise_is_installed | default(false)) and
        (current_splunk_enterprise_version is version('9.4.0', '<'))
      ) or
      (
        (not splunk_enterprise_is_installed | default(false)) and
        (splunk_enterprise_version is version('9.4.0', '<'))
      )

- name: Include task to configure cgroupv2
  ansible.builtin.include_tasks: manage_cgroup_v2.yml
  when:
    - running_kernel_cgroup_version == 'cgroupv2' or
      supported_kernel_cgroup_version == 'cgroupv2'
    - (
        (splunk_enterprise_is_installed | default(false)) and
        (current_splunk_enterprise_version is version('9.4.0', '>='))
      ) or
      (
        (not splunk_enterprise_is_installed | default(false)) and
        (splunk_enterprise_version is version('9.4.0', '>='))
      )