---
# tasks file for cca.core.linux
#
# Description:
#
# Prerequisite:
#
# Roger Lindquist (github.com/rlinq)
#
# Release: 2024.1.1

- name: Get cgroup version support
  ansible.builtin.command:
    cmd: |
      grep -c "group2 /sys/fs/cgroup cgroup2" /etc/mtab
  register: cgroup_version_result
  changed_when: false
  failed_when:
    - cgroup_version_result.rc > 1

- name: Set kernel supported cgroup version
  ansible.builtin.set_fact:
    kernel_supported_cgroup_version: "{{ 'cgroupv1' if cgroup_version_result.stdout | int == 0 else 'cgroupv2' }}"

- name: Get current configured systemd cgroup version
  ansible.builtin.command:
    cmd: |
      grep -c "cgroup /sys/fs/cgroup/systemd cgroup" /etc/mtab
  register: systemd_cgroup_version_result
  changed_when: false
  failed_when:
    - systemd_cgroup_version_result.rc > 1

- name: Set current systemd cgroup version
  ansible.builtin.set_fact:
    current_systemd_cgroup_version: "{{ 'cgroupv1' if systemd_cgroup_version_result.stdout | int == 1 else 'cgroupv2' }}"

- name: Block for debian based hosts
  block:
    - name: Configure legacy cgroup version until Splunk supports cgroupv2
      ansible.builtin.lineinfile:
        backrefs: true
        path: /etc/default/grub
        regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
        line: '\1 systemd.unified_cgroup_hierarchy=0"'

    - name: Update Grub
      ansible.builtin.command:
        cmd: |
          update-grub
  when:
    - cca_splunk_systemd_cgroup_support == 'cgroupv1'
    - current_systemd_cgroup_version != 'cgroupv1'
    - ansible_distribution == 'Debian' or
      ansible_distribution == 'Ubuntu'
  notify: notify server reboot

- name: Configure legacy cgroup version until Splunk supports cgroupv2
  ansible.builtin.command:
    cmd: |
      grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
  when:
    - cca_splunk_systemd_cgroup_support == 'cgroupv1'
    - current_systemd_cgroup_version != 'cgroupv1'
    - ansible_distribution != 'Debian'
    - ansible_distribution != 'Ubuntu'
  register: grubby_kernel_update_status
  notify: notify server reboot

- name: Copy cgroup handler script
  ansible.builtin.copy:
    src: "usr/local/bin/cca_cgroup_version_handler.sh"
    dest: "/usr/local/bin/cca_cgroup_version_handler.sh"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0750'

- name: Configure cgroup-daemon service in /etc/systemd/system/cca_cgroup_version_daemon.service
  ansible.builtin.template:
    src: "etc/systemd/system/cca_cgroup_version_daemon.service.j2"
    dest: "/etc/systemd/system/cca_cgroup_version_daemon.service"
    mode: '0644'

- name: Configure systemd for the new service
  ansible.builtin.systemd:
    name: "cca_cgroup_version_daemon.service"
    enabled: true
    daemon_reload: true

- name: Trigger restart if pending from cgroups update
  meta: flush_handlers

- name: Include role for reboot handler
  ansible.builtin.include_tasks:
    file: server_reboot_handler.yml
  when:
   - grubby_kernel_update_status.changed | default(false)
