---
# tasks file for cca.core.splunk
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2024.1.2

- name: Include task to check pending actions
  ansible.builtin.include_tasks: check_pending_actions.yml

- name: Reload Deployment Server
  block:
    - name: Include tasks to login to splunk cli
      ansible.builtin.include_tasks:
        splunk_login.yml

    - name: Reload deploy-server to notify clients of new apps
      ansible.builtin.shell: "{{ splunk_path }}/bin/splunk reload deploy-server -timeout {{ reload_deploy_server_timeout | default(900) }}"

    - name: Cleanup state file for deployment apps push
      ansible.builtin.file:
        path: "{{ deployment_server_reload_pending }}"
        state: absent
  when:
    - stat_deployment_server_reload_pending.stat.exists
    - not stat_splunkd_restart_pending.stat.exists

- name: Restart Deployment Server
  ansible.builtin.include_tasks: restart_splunkd.yml
  when:
    - stat_splunkd_restart_pending.stat.exists
