# Playbook to deploy deployment-apps to splunk instances
# Initial
#
# REPO_TYPE=onboarding
# MENU_DESC=Deploy deployment-apps to Deployment Servers
# EXTRA_VARS=hide_password(true) accept_deployment_app_removal(false)

- name: Initialize playbook run on manager server - Deploy Deployment Apps
  hosts: manager
  connection: local
  strategy: linear
  any_errors_fatal: true
  pre_tasks:
    - include_role:
        name: cca.core.control
        tasks_from:
          initialize.yml
      vars:
        target: "deploy_deployment-apps"

# Deploy deployment-apps to Splunk servers
- hosts: deployment_servers
  become: true
  become_method: sudo
  become_user: splunk
  gather_facts: false
  any_errors_fatal: true
  
  pre_tasks:
    - setup:
        gather_subset: 'network'

    - include_role:
        name: cca.core.control
        tasks_from:
          pre_deployment_tasks.yml

  tasks:
    - name: Include onboarding role for deployment-apps
      include_role:
        name: cca.splunk.onboarding
      vars:
        - deploy_scope: "deployment-apps"

    - name: Include onboarding role for apps to deployment server
      include_role:
        name: cca.splunk.onboarding
      vars:
        - deploy_scope: "apps"
    

  post_tasks:
    - include_role:
        name: cca.core.splunk
        tasks_from:
          reload_deployment_server.yml

    - include_role:
        name: cca.core.control
        tasks_from:
          post_deployment_tasks.yml

# Finalize playbook run on manager server
- hosts: manager
  connection: local
  strategy: linear
  pre_tasks:
    - include_role:
        name: cca.core.control
        tasks_from:
          finalize.yml
      vars:
        target: "deploy_deployment-apps"
