---
# REPO_TYPE=infrastructure
# MENU_DESC=Upgrade Cluster Manager and all non clustered servers.
# EXTRA_VARS=cca_splunk_enterprise_upgrade(false) \
# upgrade_check(true) \
# upgrade_cluster_manager(true)

# Upgrades Cluster Manager and all non clustered servers, inlcuding standalone
# search head servers.

# Start upgrade with cluster manager, if you have standalone search head servers
# in your instructure. If you don't have standalone search head servers, set
# upgrade_cluster_manager to false, and run this playbook on the non clustered
# servers.

#     ____ _           _              __  __
#    / ___| |_   _ ___| |_ ___ _ __  |  \/  | __ _ _ __   __ _  __ _  ___ _ __
#   | |   | | | | / __| __/ _ \ '__| | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
#   | |___| | |_| \__ \ ||  __/ |    | |  | | (_| | | | | (_| | (_| |  __/ |
#    \____|_|\__,_|___/\__\___|_|    |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|
#                                                              |___/


- name: Upgrade cluster managers
  hosts: cluster_managers
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ splunk_user }}"
  gather_facts: false
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset: 'network'
      when:
        - upgrade_cluster_manager | default(true)

    - name: Include role to store current splunk version
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          get_splunk_version.yml

    - name: Upgrade Splunk Enterprise
      ansible.builtin.include_role:
        name: cca.splunk.enterprise-install
      when:
        - upgrade_cluster_manager | default(true)

    - name: Run post upgrade tasks
      ansible.builtin.include_role:
        name: cca.core.control
        tasks_from:
          post_upgrade_tasks.yml
      when:
        - upgrade_cluster_manager | default(true)


# Upgrade non clustered servers in availability group 1
#       _             _ _       _     _ _ _ _          ____                         _
#      / \__   ____ _(_) | __ _| |__ (_) (_) |_ _   _ / ___|_ __ ___  _   _ _ __   / |
#     / _ \ \ / / _` | | |/ _` | '_ \| | | | __| | | | |  _| '__/ _ \| | | | '_ \  | |
#    / ___ \ V / (_| | | | (_| | |_) | | | | |_| |_| | |_| | | | (_) | |_| | |_) | | |
#   /_/   \_\_/ \__,_|_|_|\__,_|_.__/|_|_|_|\__|\__, |\____|_|  \___/ \__,_| .__/  |_|
#                                               |___/                      |_|

- name: Upgrade non clustered servers in availability group 1
  hosts: non_clustered_splunk_servers:&ag1
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ splunk_user }}"
  gather_facts: false
  pre_tasks:
    - name: Include role to get splunk status - AG1
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          get_splunk_status.yml

    - name: Include role to install splunk enterprise - AG1
      ansible.builtin.include_role:
        name: cca.splunk.enterprise-install
      when:
        - splunk_ok_status_flag | default(false)


# Upgrade non clustered servers in availability group 2
#       _             _ _       _     _ _ _ _          ____                         ____
#      / \__   ____ _(_) | __ _| |__ (_) (_) |_ _   _ / ___|_ __ ___  _   _ _ __   |___ \
#     / _ \ \ / / _` | | |/ _` | '_ \| | | | __| | | | |  _| '__/ _ \| | | | '_ \    __) |
#    / ___ \ V / (_| | | | (_| | |_) | | | | |_| |_| | |_| | | | (_) | |_| | |_) |  / __/
#   /_/   \_\_/ \__,_|_|_|\__,_|_.__/|_|_|_|\__|\__, |\____|_|  \___/ \__,_| .__/  |_____|
#                                               |___/                      |_|

- name: Upgrade non clustered servers in availability group 2
  hosts: non_clustered_splunk_servers:&ag2
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ splunk_user }}"
  gather_facts: false
  pre_tasks:
    - name: Include role to get splunk status - AG2
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          get_splunk_status.yml

    - name: Include role to install splunk enterprise - AG2
      ansible.builtin.include_role:
        name: cca.splunk.enterprise-install
      when:
        - splunk_ok_status_flag | default(false)

# Upgrade non clustered servers in availability group 3

#       _             _ _       _     _ _ _ _          ____                         _____
#      / \__   ____ _(_) | __ _| |__ (_) (_) |_ _   _ / ___|_ __ ___  _   _ _ __   |___ /
#     / _ \ \ / / _` | | |/ _` | '_ \| | | | __| | | | |  _| '__/ _ \| | | | '_ \    |_ \
#    / ___ \ V / (_| | | | (_| | |_) | | | | |_| |_| | |_| | | | (_) | |_| | |_) |  ___) |
#   /_/   \_\_/ \__,_|_|_|\__,_|_.__/|_|_|_|\__|\__, |\____|_|  \___/ \__,_| .__/  |____/
#                                               |___/                      |_|

- name: Upgrade non clustered servers in availability group 3
  hosts: non_clustered_splunk_servers:&ag3
  become: true
  become_method: ansible.builtin.sudo
  become_user: "{{ splunk_user }}"
  pre_tasks:
    - name: Include role to get splunk status - AG3
      ansible.builtin.include_role:
        name: cca.core.splunk
        tasks_from:
          get_splunk_status.yml

    - name: Include role to install splunk enterprise - AG3
      ansible.builtin.include_role:
        name: cca.splunk.enterprise-install
      when:
        - splunk_ok_status_flag | default(false)
