---
# tasks file for cca.splunk.role-searchhead
#
# Description:
#
# Prerequisite:
#
# Author: Roger Lindquist (github.com/rlinq)
#
# Release: 2022.2.1

- name: Verify that Splunk is running
  ansible.builtin.command:
    cmd: "timeout 5 {{ splunk_path }}/bin/splunk status --accept-license --answer-yes --no-prompt"
  register: splunk_status_result
  until: splunk_status_result.rc == 0
  retries: 5
  delay: 10
  changed_when: false
  check_mode: false

- name: Splunk login
  ansible.builtin.command:
    cmd: "timeout 60 {{ splunk_path }}/bin/splunk login --accept-license --answer-yes --no-prompt -auth '{{ splunk_cli_user }}:{{ splunk_cli_user_password }}'"
  register: splunk_login_result
  no_log: "{{ hide_password }}"
  failed_when: false
  changed_when: false
  until: splunk_login_result.rc == 0
  retries: 5
  check_mode: false

- name: Debug any error and fail task if login wasn't successful
  ansible.builtin.debug:
    msg: >-
      Splunk command or login failed with the reason (
      {{ splunk_login_result.stderr | default('Skipped task, disregard this stderr message') }} )
      Splunk command had an unexpected result if this is not blank (
      {{ splunk_login_result.stdout | default('Skipped task, disregard this stderr message') }} )
  when:
    - splunk_login_result.rc > 0
  failed_when:
    - splunk_login_result.rc > 0
